### ISSUE TITLE
"Не удалось настроить" сообщение в home assistant

### ISSUE THREAD

**Issue by F0min-ivan** [dext0r/yandex_smart_home#421]
Home Assistant 2022 12.3

Все было настроено и работало

Logger: homeassistant.util.json
Source: util/json.py:39
First occurred: 21:38:42 (1 occurrences)
Last logged: 21:38:42

Could not parse JSON content: /config/.storage/yandex_smart_home.cache
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

Logger: homeassistant.config_entries
Source: util/json.py:45
First occurred: 21:38:42 (1 occurrences)
Last logged: 21:38:42

Error setting up entry Yandex Smart Home for yandex_smart_home
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 372, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/yandex_smart_home/__init__.py", line 208, in async_setup_entry
    await config.async_init()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 35, in async_init
    await self.cache.async_load()
  File "/config/custom_components/yandex_smart_home/helpers.py", line 127, in async_load
    data = await self._store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 143, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: unexpected character: line 1 column 1 (char 0)

**Comment by dext0r** [comment]
Приложите файл /config/.storage/yandex_smart_home.cache сюда. После этого его можно безопасно удалить и компонент заработает.

**Comment by F0min-ivan** [comment]
[yandex_smart_home.zip](https://github.com/dext0r/yandex_smart_home/files/10221815/yandex_smart_home.zip)

**Comment by F0min-ivan** [comment]
переименовал данный файл заработало

**Comment by F0min-ivan** [comment]
Месяц назад перевел HA на мини ПК. Соответственно устанавливал HA заново и восстанавливал через полный бэкап настроек средствами HA. Заметил что некоторые дополнения слетели типа NodeRed  и прочие вещи неприятные вещи. Может тогда и поломался этот файл

**Comment by dext0r** [comment]
> Месяц назад перевел HA на мини ПК. Соответственно устанавливал HA заново и восстанавливал через полный бэкап настроек средствами HA. Заметил что некоторые дополнения слетели типа NodeRed и прочие вещи неприятные вещи. Может тогда и поломался этот файл

Видимо с резервным копированием что-то пошло не так, потому что файл содержит только нули. В компоненте эту ситуацию никак не обработать, потому что используется встроенный в ХА способ работы с JSON.
