### ISSUE TITLE
yandex_smart_home/notifier.py", line 288, in _state_change_listener

### ISSUE THREAD

**Issue by Mrboob58** [dext0r/yandex_smart_home#545]
HA показывает ошибки:

2024-09-01T16:05:51 2024-09-01 13:05:51.172 ERROR (ImportExecutor_0) [homeassistant] Error doing job: Task exception was never retrieved (None)

2024-09-01T16:05:51 Traceback (most recent call last):

2024-09-01T16:05:51 File "/config/custom_components/yandex_smart_home/notifier.py", line 288, in _state_change_listener

2024-09-01T16:05:51 await asyncio.gather(*[n.async_event_handler(event) for n in hass.data[DOMAIN][NOTIFIERS]])

2024-09-01T16:05:51 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-09-01T16:05:51 File "/usr/local/lib/python3.12/asyncio/tasks.py", line 831, in gather

2024-09-01T16:05:51 fut = ensure_future(arg, loop=loop)

2024-09-01T16:05:51 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-09-01T16:05:51 File "/usr/local/lib/python3.12/asyncio/tasks.py", line 693, in ensure_future

2024-09-01T16:05:51 loop = events.get_event_loop()

2024-09-01T16:05:51 ^^^^^^^^^^^^^^^^^^^^^^^

2024-09-01T16:05:51 loop = events.get_event_loop()

2024-09-01T16:05:51 ^^^^^^^^^^^^^^^^^^^^^^^

2024-09-01T16:05:51 File "/usr/local/lib/python3.12/asyncio/events.py", line 702, in get_event_loop

2024-09-01T16:05:51 raise RuntimeError('There is no current event loop in thread %r.'

2024-09-01T16:05:51 RuntimeError: There is no current event loop in thread 'SyncWorker_0'.

**Comment by dext0r** [comment]
Удалите интеграцию hass_diagnostics (#530)

**Comment by Mrboob58** [comment]
> Удалите интеграцию hass_diagnostics (#530)

такой интеграции у меня нет

**Comment by Mrboob58** [comment]
> > такой интеграции у меня нет
> 
> Покажите список установленных сторонних компонентов (содержимое каталога custom_components)

![Снимок экрана 2024-10-26 025218](https://github.com/user-attachments/assets/490348e8-792b-4bd8-8b30-609a6c22e401)

**Comment by dext0r** [comment]
Попробуйте для теста отключить интеграцию sonoff и посмотреть будет ли повторятся ошибка.
И ещё вопрос: насколько часто эта ошибка возникает?

**Comment by Mrboob58** [comment]
> Попробуйте для теста отключить интеграцию sonoff и посмотреть будет ли повторятся ошибка. И ещё вопрос: насколько часто эта ошибка возникает?

Отключил и удалил sonoff lan, ошибка снова появилась через минут 10/15 работы HA.

**Comment by Mrboob58** [comment]
сбросил и перенастроил HA с нуля, все поставил заново, второй день пока и ошибки нет. Только постоянно это предупреждение - MEDIA_TYPE_CHANNEL was used from yandex_smart_home, this is a deprecated constant which will be removed in HA Core 2025.10. Use MediaType.CHANNEL instead, please create a bug report at https://github.com/dext0r/yandex_smart_home/issues

**Comment by dext0r** [comment]
> сбросил и перенастроил HA с нуля, все поставил заново, второй день пока и ошибки нет

Хорошо, тогда ишью закрываю. Пишите если повторится.

>  Только постоянно это предупреждение - MEDIA_TYPE_CHANNEL was used from yandex_smart_home

Будет исправлено в следующей версии, это просто предупреждение.
